language: php
sudo: false

matrix:
    fast_finish: true
    include:
        - php: 5.5
        - php: 5.6
#        - php: nightly
#    allow_failures:
#        - php: nightly

install:
    - pecl install -f swoole
    - composer self-update
    - composer install

script:
    - phpunit --coverage-text
