language: php

matrix:
    include:
        - php: 5.5
#        - php: 5.6
#        - php: nightly
#    allow_failures:
#        - php: nightly

install:
    - pecl install -f swoole
    - echo "extension=swoole.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
    - composer self-update
    - composer install