language: php

matrix:
    include:
        - php: 5.5
        - php: 5.6
        - php: nightly
    allow_failures:
        - php: nightly

before_script:
    - sudo pecl install swoole
    - echo "extension=<extension>.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
    - composer self-update

install:
    - composer install